#!/usr/bin/env bash
# Generate production secrets into the repo-root .env (gitignored).
#
# Usage:
#   ./development/gen-secrets.sh           # write .env (fail if it exists)
#   ./development/gen-secrets.sh --force   # overwrite existing .env
#   ./development/gen-secrets.sh --stdout  # print only (do not write)
#
# Docker Compose loads .env automatically from the project directory for
# ${VAR} interpolation. Then:
#   docker compose up -d
#   # or: docker compose --env-file .env up -d
#
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
GEN="$(CDPATH= cd -- "$(dirname "$0")" && pwd)/gen-password.sh"
OUT="${ROOT}/.new-env"
FORCE=0
STDOUT_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force|-f) FORCE=1; shift ;;
    --stdout|-p|--print) STDOUT_ONLY=1; shift ;;
    -h|--help)
      sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ "${STDOUT_ONLY}" -eq 0 && -f "${OUT}" && "${FORCE}" -eq 0 ]]; then
  echo "${OUT} already exists. Pass --force to overwrite, or --stdout to print." >&2
  exit 1
fi

DB_PASSWORD="$("$GEN" 32)"
S3_SECRET="$("$GEN" 32)"
JWT_PEPPER="$("$GEN" --url 48)"
MAIL_PASSWORD="$("$GEN" 24)"

# Keep Postgres and Quarkus passwords in sync; MinIO root and S3 secret in sync.
CONTENT=$(cat <<EOF
# Generated by development/gen-secrets.sh — never commit this file
# Compose reads this automatically from the project root.

# Database (postgres service + app)
POSTGRES_USER=yaadbuzz
POSTGRES_PASSWORD=${DB_PASSWORD}
QUARKUS_DATASOURCE_USERNAME=yaadbuzz
QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}

# MinIO / S3
MINIO_ROOT_USER=yaadbuzz
MINIO_ROOT_PASSWORD=${S3_SECRET}
YAADBUZZ_S3_ACCESS_KEY=yaadbuzz
YAADBUZZ_S3_SECRET_KEY=${S3_SECRET}

# App
YAADBUZZ_JWT_REFRESH_PEPPER=${JWT_PEPPER}
YAADBUZZ_MAIL_PASSWORD=${MAIL_PASSWORD}
YAADBUZZ_PUBLIC_URL=https://yaadbuzz.ir

# Optional social login (fill in after creating OAuth apps)
# YAADBUZZ_OAUTH_GOOGLE_ENABLED=true
# YAADBUZZ_OAUTH_GOOGLE_CLIENT_ID=
# YAADBUZZ_OAUTH_GOOGLE_CLIENT_SECRET=
# YAADBUZZ_OAUTH_GITHUB_ENABLED=true
# YAADBUZZ_OAUTH_GITHUB_CLIENT_ID=
# YAADBUZZ_OAUTH_GITHUB_CLIENT_SECRET=
# YAADBUZZ_OAUTH_TELEGRAM_ENABLED=true
# YAADBUZZ_OAUTH_TELEGRAM_BOT_TOKEN=
# YAADBUZZ_OAUTH_TELEGRAM_BOT_USERNAME=YourBotUsername

# Optional Sentry
# QUARKUS_LOG_SENTRY_ENABLED=true
# SENTRY_DSN=https://…@o….ingest.sentry.io/…
# VITE_SENTRY_DSN=https://…@o….ingest.sentry.io/…
EOF
)

if [[ "${STDOUT_ONLY}" -eq 1 ]]; then
  printf '%s\n' "${CONTENT}"
else
  printf '%s\n' "${CONTENT}" > "${OUT}"
  chmod 600 "${OUT}"
  echo "Wrote ${OUT} (mode 600)."
  echo "Run: docker compose up -d"
fi
