#!/usr/bin/env bash
# Generate production secrets into the repo-root .env (gitignored).
#
# Usage:
#   ./development/gen-secrets.sh           # write .env (fail if it exists)
#   ./development/gen-secrets.sh --force   # overwrite existing .env
#   ./development/gen-secrets.sh --stdout  # print only (do not write)
#
# Docker Compose loads .env automatically from the project directory for
# ${VAR} interpolation. Then:
#   docker compose up -d --build
#   # or: docker compose --env-file .env up -d
#
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
GEN="$(CDPATH= cd -- "$(dirname "$0")" && pwd)/gen-password.sh"
OUT="${ROOT}/.env"
FORCE=0
STDOUT_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force|-f) FORCE=1; shift ;;
    --stdout|-p|--print) STDOUT_ONLY=1; shift ;;
    -h|--help)
      sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ "${STDOUT_ONLY}" -eq 0 && -f "${OUT}" && "${FORCE}" -eq 0 ]]; then
  echo "${OUT} already exists. Pass --force to overwrite, or --stdout to print." >&2
  exit 1
fi

DB_PASSWORD="$("$GEN" 32)"
S3_SECRET="$("$GEN" 32)"
JWT_PEPPER="$("$GEN" --url 48)"
MAIL_PASSWORD="$("$GEN" 24)"

# Keep Postgres/Quarkus DB passwords and MinIO root/S3 secret in sync.
CONTENT=$(cat <<EOF
# Generated by development/gen-secrets.sh — never commit this file
# Compose reads this automatically from the project root.

# --- Docker image (compose app service) ---
APP_IMAGE=hosseinmp762/yaadbuzz
IMAGE_TAG=local
APP_PULL_POLICY=missing

# --- Database (postgres service + app) ---
POSTGRES_USER=yaadbuzz
POSTGRES_PASSWORD=${DB_PASSWORD}
QUARKUS_DATASOURCE_USERNAME=yaadbuzz
QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
# Used by quarkus:dev / standalone JVM; compose app sets jdbc URL inline.
QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/yaadbuzz
QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=elasticsearch:9200

# --- MinIO / S3 ---
MINIO_ROOT_USER=yaadbuzz
MINIO_ROOT_PASSWORD=${S3_SECRET}
YAADBUZZ_S3_ENDPOINT=http://minio:9000
YAADBUZZ_S3_PUBLIC_ENDPOINT=https://yaadbuzz.ir
YAADBUZZ_S3_ACCESS_KEY=yaadbuzz
YAADBUZZ_S3_SECRET_KEY=${S3_SECRET}
YAADBUZZ_S3_BUCKET=yaadbuzz

# --- App URLs ---
YAADBUZZ_PUBLIC_URL=https://yaadbuzz.ir
YAADBUZZ_SOURCE_URL=https://github.com/hosseinmp76/yaadbuzz

# --- Auth (reserved; wire in TokenService when used) ---
YAADBUZZ_JWT_REFRESH_PEPPER=${JWT_PEPPER}

# --- Mail (set YAADBUZZ_MAIL_MOCK=false and fill SMTP for production) ---
YAADBUZZ_MAIL_MOCK=true
YAADBUZZ_MAIL_HOST=localhost
YAADBUZZ_MAIL_PORT=1025
YAADBUZZ_MAIL_USERNAME=
YAADBUZZ_MAIL_PASSWORD=${MAIL_PASSWORD}
YAADBUZZ_MAIL_FROM=Yaadbuzz <noreply@yaadbuzz.ir>
YAADBUZZ_MAIL_START_TLS=OPTIONAL

# --- Google OAuth (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/google) ---
YAADBUZZ_OAUTH_GOOGLE_ENABLED=false
YAADBUZZ_OAUTH_GOOGLE_CLIENT_ID=
YAADBUZZ_OAUTH_GOOGLE_CLIENT_SECRET=

# --- GitHub OAuth (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/github) ---
YAADBUZZ_OAUTH_GITHUB_ENABLED=false
YAADBUZZ_OAUTH_GITHUB_CLIENT_ID=
YAADBUZZ_OAUTH_GITHUB_CLIENT_SECRET=

# --- Telegram OIDC (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/telegram) ---
# Client ID / Secret from BotFather → Bot Settings → Web Login (not the bot API token).
YAADBUZZ_OAUTH_TELEGRAM_ENABLED=false
YAADBUZZ_OAUTH_TELEGRAM_CLIENT_ID=
YAADBUZZ_OAUTH_TELEGRAM_CLIENT_SECRET=

# --- Sentry (optional) ---
QUARKUS_LOG_SENTRY_ENABLED=false
SENTRY_DSN=
SENTRY_ENVIRONMENT=production
# Frontend (build-time via Quinoa; set before image build if used):
# VITE_SENTRY_DSN=
# VITE_SENTRY_ENVIRONMENT=production
# VITE_SITE_URL=https://yaadbuzz.ir
# VITE_SOURCE_URL=https://github.com/hosseinmp76/yaadbuzz
EOF
)

if [[ "${STDOUT_ONLY}" -eq 1 ]]; then
  printf '%s\n' "${CONTENT}"
else
  printf '%s\n' "${CONTENT}" > "${OUT}"
  chmod 600 "${OUT}"
  echo "Wrote ${OUT} (mode 600)."
  echo "Edit OAuth/mail values, then: docker compose up -d --build"
fi
