#!/usr/bin/env bash
# Generate secrets into the repo-root .env (gitignored).
#
# Default (--local): hostnames for ./mvnw quarkus:dev on your machine while
# dependencies run via `docker compose up -d postgres elasticsearch minio minio-init`
# (Compose publishes 5432/9200/9000 on localhost). The compose *app* service
# hardcodes docker network hostnames (postgres, elasticsearch, minio) in
# docker-compose.yml — it does not read these JDBC/ES/S3 host vars from .env.
#
# Usage:
#   ./development/gen-secrets.sh              # local dev .env (default)
#   ./development/gen-secrets.sh --prod         # production URLs (yaadbuzz.ir)
#   ./development/gen-secrets.sh --force        # overwrite existing .env
#   ./development/gen-secrets.sh --stdout     # print only (do not write)
#
# Docker Compose loads .env automatically from the project directory for
# ${VAR} interpolation (passwords, OAuth, public URL, etc.).
#
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
GEN="$(CDPATH= cd -- "$(dirname "$0")" && pwd)/gen-password.sh"
OUT="${ROOT}/.env"
FORCE=0
STDOUT_ONLY=0
PROFILE=local

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force|-f) FORCE=1; shift ;;
    --stdout|-p|--print) STDOUT_ONLY=1; shift ;;
    --prod|--production) PROFILE=prod; shift ;;
    --local|--dev) PROFILE=local; shift ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ "${PROFILE}" == prod ]]; then
  PUBLIC_URL=https://yaadbuzz.ir
  S3_PUBLIC_ENDPOINT=https://yaadbuzz.ir
  SENTRY_ENV=production
  PROFILE_LABEL=production
else
  PUBLIC_URL=http://localhost:8080
  S3_PUBLIC_ENDPOINT=http://localhost:9000
  SENTRY_ENV=development
  PROFILE_LABEL="local development"
fi

if [[ "${STDOUT_ONLY}" -eq 0 && -f "${OUT}" && "${FORCE}" -eq 0 ]]; then
  echo "${OUT} already exists. Pass --force to overwrite, or --stdout to print." >&2
  exit 1
fi

DB_PASSWORD="$("$GEN" 32)"
METABASE_DB_PASSWORD="$("$GEN" 32)"
S3_SECRET="$("$GEN" 32)"
JWT_PEPPER="$("$GEN" --url 48)"
MAIL_PASSWORD="$("$GEN" 24)"

# Keep Postgres/Quarkus DB passwords and MinIO root/S3 secret in sync.
CONTENT=$(cat <<EOF
# Generated by development/gen-secrets.sh (${PROFILE_LABEL}) — never commit this file
# Compose reads this automatically from the project root.
#
# Local dev: docker compose up -d postgres elasticsearch minio minio-init && ./mvnw quarkus:dev
# Production: edit YAADBUZZ_PUBLIC_URL / OAuth / mail if needed, then docker compose up -d --build
# Regenerate for prod URLs: ./development/gen-secrets.sh --prod --force

# --- Docker image (compose app service) ---
APP_IMAGE=hosseinmp762/yaadbuzz
IMAGE_TAG=local
APP_PULL_POLICY=missing

# --- Database (postgres service + app) ---
POSTGRES_USER=yaadbuzz
POSTGRES_PASSWORD=${DB_PASSWORD}
QUARKUS_DATASOURCE_USERNAME=yaadbuzz
QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
# Host-reachable URLs for quarkus:dev / JVM on the host (Compose maps ports to localhost).
# The compose app container overrides these with docker service names in docker-compose.yml.
QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost:5432/yaadbuzz
QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=localhost:9200

# --- Metabase (dedicated Postgres role; not the app datasource user) ---
METABASE_DB_USER=metabase
METABASE_DB_PASSWORD=${METABASE_DB_PASSWORD}

# --- MinIO / S3 ---
MINIO_ROOT_USER=yaadbuzz
MINIO_ROOT_PASSWORD=${S3_SECRET}
YAADBUZZ_S3_ENDPOINT=http://localhost:9000
YAADBUZZ_S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
YAADBUZZ_S3_ACCESS_KEY=yaadbuzz
YAADBUZZ_S3_SECRET_KEY=${S3_SECRET}
YAADBUZZ_S3_BUCKET=yaadbuzz

# --- App URLs ---
YAADBUZZ_PUBLIC_URL=${PUBLIC_URL}
YAADBUZZ_SOURCE_URL=https://github.com/hosseinmp76/yaadbuzz

# --- Auth (reserved; wire in TokenService when used) ---
YAADBUZZ_JWT_REFRESH_PEPPER=${JWT_PEPPER}

# --- Mail (set YAADBUZZ_MAIL_MOCK=false and fill SMTP for production) ---
YAADBUZZ_MAIL_MOCK=true
YAADBUZZ_MAIL_HOST=localhost
YAADBUZZ_MAIL_PORT=1025
YAADBUZZ_MAIL_USERNAME=
YAADBUZZ_MAIL_PASSWORD=${MAIL_PASSWORD}
YAADBUZZ_MAIL_FROM=Yaadbuzz <noreply@yaadbuzz.ir>
YAADBUZZ_MAIL_START_TLS=OPTIONAL

# --- Google OAuth (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/google) ---
YAADBUZZ_OAUTH_GOOGLE_ENABLED=false
YAADBUZZ_OAUTH_GOOGLE_CLIENT_ID=
YAADBUZZ_OAUTH_GOOGLE_CLIENT_SECRET=

# --- GitHub OAuth (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/github) ---
YAADBUZZ_OAUTH_GITHUB_ENABLED=false
YAADBUZZ_OAUTH_GITHUB_CLIENT_ID=
YAADBUZZ_OAUTH_GITHUB_CLIENT_SECRET=

# --- Telegram OIDC (redirect: \${YAADBUZZ_PUBLIC_URL}/api/auth/oauth/telegram) ---
# Client ID / Secret from BotFather → Bot Settings → Web Login (not the bot API token).
YAADBUZZ_OAUTH_TELEGRAM_ENABLED=false
YAADBUZZ_OAUTH_TELEGRAM_CLIENT_ID=
YAADBUZZ_OAUTH_TELEGRAM_CLIENT_SECRET=

# --- Sentry (optional) ---
QUARKUS_LOG_SENTRY_ENABLED=false
SENTRY_DSN=
SENTRY_ENVIRONMENT=${SENTRY_ENV}
# Frontend (build-time via Quinoa; set before image build if used):
# VITE_SENTRY_DSN=
# VITE_SENTRY_ENVIRONMENT=${SENTRY_ENV}
# VITE_SITE_URL=${PUBLIC_URL}
# VITE_SOURCE_URL=https://github.com/hosseinmp76/yaadbuzz
EOF
)

if [[ "${STDOUT_ONLY}" -eq 1 ]]; then
  printf '%s\n' "${CONTENT}"
else
  printf '%s\n' "${CONTENT}" > "${OUT}"
  chmod 600 "${OUT}"
  echo "Wrote ${OUT} (mode 600, ${PROFILE_LABEL})."
  if [[ "${PROFILE}" == local ]]; then
    echo "Local dev: docker compose up -d postgres elasticsearch minio minio-init && ./mvnw quarkus:dev"
  else
    echo "Production: edit OAuth/mail values, then docker compose up -d --build"
  fi
fi
