-- Yearbook customization on team
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_title VARCHAR(255);
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_subtitle VARCHAR(255);
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_dedication TEXT;
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_theme VARCHAR(32) NOT NULL DEFAULT 'CLASSIC';
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_show_members BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_show_tributes BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_show_characteristics BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_show_memories BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE team ADD COLUMN IF NOT EXISTS yearbook_show_awards BOOLEAN NOT NULL DEFAULT TRUE;
